# Copyright (c) 2017-2020 Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.

# Specify the compiler flags
#CXX ?= g++

CXXFLAGS += -std=c++11 -fPIC -march=x86-64


# Include paths
INCLUDES += -I $(SNPE_ROOT)/include/zdl -I $(SNPE_ROOT)/include/SNPE

# Specify the paths to the libraries
LDFLAGS  += -L $(SNPE_ROOT)/lib/x86_64-linux-clang
# opencv and snpe
INCLUDES_O += -I include
OPENCV_CFLAGS = `pkg-config --cflags opencv4`
OPENCV_LIBS = `pkg-config --libs opencv4`


# Specify the link libraries
LLIBS    += -lSNPE 


# Specify the target
PROGRAM  := snpe-sample
SRC_DIR  := src/
OBJ_DIR  := obj/local/x86_64-linux-clang

# Specify the source list and the object directories.
# The source file is in the 'jni' directory to be compatible with the
# Android NDK structure.
# Get the list of source files including the directory
# SRC      := $(wildcard $(SRC_DIR)/*.cpp) # whole cpp
# List of specific .cpp files
SRC := $(SRC_DIR)/main.cpp \
       $(SRC_DIR)/SNPETask.cpp \
       $(SRC_DIR)/YOLOv5.cpp \
       $(SRC_DIR)/YOLOv5Impl.cpp 

# Generate the output names by substituting the object dir for the source dir
OBJS     := $(subst $(SRC_DIR),$(OBJ_DIR),$(subst .cpp,.o,$(SRC)))

default: all
all: $(OBJ_DIR)/$(PROGRAM)

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp $(OBJ_DIR)
	$(CXX) $(OPENCV_CFLAGS) -c $(CXXFLAGS) $(INCLUDES) $(INCLUDES_O) $< -o $@

$(OBJ_DIR)/$(PROGRAM): $(OBJS)
	$(CXX) $(OPENCV_CFLAGS) $(LDFLAGS) $^ $(LLIBS) -o $@  $(OPENCV_LIBS)

clean:
	-rm -f $(OBJS) $(PROGRAM).o
	-rm -f $(PROGRAM)

$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

.PHONY: default clean
